<a href="https://colab.research.google.com/github/sruthi1996/DeepLearning/blob/master/p1ch3_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
a = [2.0, 3.0, 2.0]

In [2]:
print(a[0])
print(a[1])

2.0
3.0


In [3]:
#reassigning Tensor
a[2] = 4.0
print(a)

[2.0, 3.0, 4.0]


In [0]:
import torch

In [10]:
a = torch.ones(4)#size
a

tensor([1., 1., 1., 1.])

In [11]:
float(a[2])#typecasting

1.0

In [0]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0


In [15]:
points = torch.tensor([5.0, 6.0, 7.0, 3.0, 2.0, 1.0])
points

tensor([5., 6., 7., 3., 2., 1.])

In [16]:
float(points[0]), float(points[1])

(5.0, 6.0)

In [17]:
#two dimensional arrays
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [19]:
points.shape

torch.Size([3, 2])

In [21]:
#matrix of zeros
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [22]:
#matrix of ones
points = torch.ones(3, 3)
points

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [0]:
#reassigning a tensor
points[2,2] = 4.0

In [26]:
points

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 4.]])

In [28]:
points = torch.tensor([[3.0, 3.0], [4.0, 5.0], [2.0, 1.0]])
points.storage()

 3.0
 3.0
 4.0
 5.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [29]:
points_storage = points.storage()
points_storage[4]

2.0

In [30]:
points.storage()[1]

3.0

In [31]:
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 3.],
        [4., 5.],
        [2., 1.]])

In [32]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()

2

In [35]:

print(second_point.size())
print(second_point.shape)
print(points.stride())

torch.Size([2])
torch.Size([2])
(2, 1)


In [36]:
points = torch.tensor([[6.0, 1.0], [5.0, 10.0], [12.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 6.,  1.],
        [10., 10.],
        [12.,  1.]])

In [39]:
points = torch.tensor([[2.0, 1.0], [6.0, 3.0], [9.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[2., 1.],
        [6., 3.],
        [9., 1.]])

In [41]:
points = torch.tensor([[3.0, 2.0], [3.0, 3.0], [2.0, 1.0]])
points

tensor([[3., 2.],
        [3., 3.],
        [2., 1.]])

In [44]:
#transpose of tensor
some_t = torch.ones(3,4,5)
transpose_t = some_t.transpose(0,2)
print(transpose_t)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


In [45]:
some_t.shape

torch.Size([3, 4, 5])

In [46]:
transpose_t.shape

torch.Size([5, 4, 3])

In [47]:
points.is_contiguous()

True

In [49]:
points = torch.tensor([[5.0, 3.0], [5.0, 3.0], [7.0, 1.0]])
points_t = points.t()
points_t

tensor([[5., 5., 7.],
        [3., 3., 1.]])

In [50]:
#check storage
points_t.storage()

 5.0
 3.0
 5.0
 3.0
 7.0
 1.0
[torch.FloatStorage of size 6]

In [51]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[5., 5., 7.],
        [3., 3., 1.]])

In [0]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [54]:
#datatype of tensor
short_points.dtype

torch.int16

In [0]:
#typecasting
double_points = torch.zeros(9, 2).double()
short_points = torch.ones(9, 2).short()

In [0]:
double_points = torch.zeros(9, 2).to(torch.double)
short_points = torch.ones(9, 2).to(dtype=torch.short)

In [57]:
points_64 = torch.rand(5, dtype=torch.double)
points_short = points_64.to(torch.short)
points_64 * points_short

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [0]:
#can revert values back to original
points = torch.tensor([[3.0, 1.0], [4.0, 3.0], [2.0, 1.0]])

In [59]:
some_list = list(range(6))
some_list[:]   
some_list[1:4]  
some_list[1:]   
some_list[:4]   
some_list[:-1]  
some_list[1:4:2]

[1, 3]

In [60]:
#changing all values of a tensor at once
a = torch.ones(3, 2)
print(a)
b = a.zero_()
print(b)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
